# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('iot-energy-optimal-route-example-topology', ['iot-energy-optimal-routing'])
    obj.source = 'iot-energy-optimal-route-example-topology.cc'

